### PR TITLE
Fix `template_rendered` signal call arguments

### PR DESCRIPTION
**Pull request by johngian**
* Use jinja2.Template instead of django_jinja.Template

### CODE REVIEW

**Comment by johngian** [comment]
Came across this one while debugging my tests in order to use ``django-jinja``.
It looks like when using ``self.assertTemplateUsed`` it tries to match the complete path to the template file rather than the relative.

This seems to be fixed when we call ``template_rendered`` signal with the ``jinja2.Template`` template rather than ``django_jinja.Template``. Also this is the case with ``django's`` internal call to ``template_render``. It uses ``django.template.base.Template`` and not ``django.template.backend.django.Template``.

**Comment by johngian** [comment]
You can reproduce the issue by running tests [1] in master.

[1] https://github.com/johngian/django-jinja/blob/fix-debug-template/testing/testapp/tests.py#L275

**Comment by niwinz** [comment]
Exposing the underlying template instance it seems a workaround instead of a solution. If that problem is fixed with the django's template implementation, it can be fixed in the same way in the django-jinja template class I think.

I'll keep this open until I can see the proper solution (maybe I'm wrong and your solution is the correct but I need time to see it).

**Comment by johngian** [comment]
Just for the reference, these are the key points regarding the way django handles this:

* It replaces ``Template._render`` with the ``instrumented_test_render`` that sends the signal intercepted in tests.
 * https://github.com/django/django/blob/master/django/test/utils.py#L105
 * https://github.com/django/django/blob/master/django/test/utils.py#L88
* Here is the ``Template._render`` method that gets overridden above. ``self`` is an instance of ``django.templates.base.Template`` class.
 * https://github.com/django/django/blob/master/django/template/base.py#L197

**Comment by johngian** [comment]
Hey @niwinz !
Is there any update on that?

**Comment by niwinz** [comment]
Should be fixed on master and next version ;)

**Pull request closed without merging**
