### PR TITLE
Django 4.0

### PR DESCRIPTION
**Pull request by wizpig64**
- Add support for Django 4.0~~b1~~, with more old-code cleanup.
  - Remove use of `django.conf.urls.url` in test app (gone in Django 4.0).
  - Set `DEFAULT_AUTO_FIELD` to avoid warnings in test app.
  - ~~Switch to `django-pipeline>=1.6.0`-style `PIPELINE` settings.~~
  - Remove `django_jinja.contrib._pipeline` package, which was deprecated in 2015.
  - Drop formal Django 3.0 and 3.1 support.
    - Projects using these versions should still function until support for 2.2 is dropped.

~~I'll be leaving this as a draft until django-pipeline is updated to support Django 4.0: https://github.com/jazzband/django-pipeline/pull/760~~

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
what about dropping 3.0

**Comment by wizpig64** [comment]
> what about dropping 3.0

Sure thing. There probably won't be any code changes though until 2.2 is dropped.

**Comment by auvipy** [comment]
yeah

**Comment by wizpig64** [comment]
I force pushed new changes dropping django 3.1, as well as the `contrib._pipeline` package, which was holding us back. If this gets merged today I'm going to release it as `v2.10.0`

**Review by auvipy — APPROVED** [review]

**Pull request merged**
