### PR TITLE
explicit version support in docs, changelog, test matrix

### PR DESCRIPTION
**Pull request by wizpig64**
django 3.0 dropped support for python 3.5, so the expanded tests here might fail. fingers crossed.

### CODE REVIEW

**Comment by wizpig64** [comment]
That didn't go as well as I thought. Despite the merged commit f209e6b saying so, Django 3.0 compatibility is not yet achieved. I'll do some more work either fixing compat with 3.0. Or, if that's not feasible without dropping support for 1.11, I'll just amend this PR to remove the django-3 assurance.

**Comment by wizpig64** [comment]
Alright, test coverage with django 3 was fixed by changing the test code (it was importing `django.shortcuts.render_to_response`, which was deprecated long ago). No user-imported code was changed, so it's still safe to call django-jinja 2.5.0 as-released compatible with django 3.0.

**Comment by wizpig64** [comment]
Thanks @auvipy  :)

**Comment by auvipy** [comment]
2.6 released!

**Pull request merged**
