### PR TITLE
Upgrade to jinja2-3.0.0

### PR DESCRIPTION
**Pull request by tomhamiltonstubber**
Upgrading to the new version of Jinja2:

https://github.com/pallets/jinja/blob/main/CHANGES.rst#version-300

This passed tests:

https://travis-ci.org/github/niwinz/django-jinja/builds/771395960

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks. any other changes needed?

**Comment by tomhamiltonstubber** [comment]
Mmmm we have a very large project and these are the changes that affected us, but I can't be sure.

Looking through the changes, I can't see anything.

**Comment by tomhamiltonstubber** [comment]
Hey can we get a release of this? Cheers

**Comment by wizpig64** [comment]
I looked through jinja's changes as well, tom's patch looks sufficient and works for my project.

**Pull request merged**
