### PR TITLE
Fix django 1.11 incompatibility

### LINKED ISSUE #194: Django==1.11 makemessages incompatibility
Hey,

when using, Django 1.11 (just released), there's the following error when attempting to run `manage.py makemessages`:

```python
Traceback (most recent call last):
  File "backend/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/project/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/project/venv/lib/python3.6/site-packages/django_jinja/management/commands/makemessages.py", line 43, in handle
    old_endblock_re = trans_real.endblock_re
AttributeError: module 'django.utils.translation.trans_real' has no attribute 'endblock_re'
```

Just letting you know.

Cheers

### PR DESCRIPTION
**Pull request by karolyi**
Hey,

this is just a quick edit, but should be able to fix #194.

### CODE REVIEW

**Comment by ShababShahriar** [comment]
I just had a look at it and it seems you need to add provision for `**kwargs` in `my_templatize()` to fix the issue properly.

```
 def my_templatize(src, origin=None, **kwargs):
     new_src = strip_whitespaces(src)
     return old_templatize(new_src, origin, **kwargs)
```

This is due to the updated `preprocess()` method in the core `makemessages.py` file of Django 1.11 which calls the method `templatize` with an additional argument `charset`.

**Comment by karolyi** [comment]
@ShababShahriar thx, I added it to the pull request. It's great to have the web editing capabilities of github, so I can edit the pull request without having to play around with git and command line. :)

**Comment by karolyi** [comment]
@niwinz , any chance of merging this request soon? This is the only thing blocking me from upgrading to Django 1.11.

**Comment by karolyi** [comment]
bumpity bump

**Comment by niwinz** [comment]
Merged and 2.3.0 version published with this fix.

**Pull request merged**
