### PR TITLE
Patch setup_test_environment to manipulate response.context.

### PR DESCRIPTION
**Pull request by glogiotatidis**
This will allow the use of response.context in tests as well as
self.assertTemplateUsed.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Original idea from http://stackoverflow.com/a/3827015

**Comment by glogiotatidis** [comment]
This test fails https://github.com/niwinz/django-jinja/blob/master/testing/testapp/tests.py#L347 which brings up the question: Since in 1.8 TEMPLATE_DEBUG is moved to TEMPLATE.OPTIONS.debug should we implement this? Does django-jinja default to the value of DEBUG in django 1.8?

**Comment by niwinz** [comment]
Thanks! It's depends, in django 1.8, TEMPLATE_DEBUG is deprecated and django-jina starts using DEBUG directly in some cases (in really the use of debug is copied from django 1.8 jinja engine).

In any case I should review it in deph for the next release for make the usage of debug in more consistent way.

**Comment by coagulant** [comment]
Actually this fixes #125 Just posting in case someone is using PyPI version 1.4.1 and not latest master :+1:

**Comment by glogiotatidis** [comment]
\ο/

**Pull request merged**
